// Generated by JFlex 1.9.1 http://jflex.de/  (tweaked for IntelliJ platform)
// source: _VyperLexer.flex

package com.vyperplugin;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;

import static com.intellij.psi.TokenType.BAD_CHARACTER;
import static com.intellij.psi.TokenType.WHITE_SPACE;
import static com.vyperplugin.psi.VyperTypes.*;


public class _VyperLexer implements FlexLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\6\1\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\11\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\2\34\1\35\1\36\1\37\1\40\1\41\4\40\1\42"+
    "\1\43\5\40\1\44\3\40\1\45\2\40\1\46\1\47"+
    "\1\50\1\51\1\52\1\0\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\40\1\64\1\65"+
    "\1\66\1\67\1\70\1\71\1\40\1\72\1\73\1\74"+
    "\1\75\1\76\1\77\1\100\1\101\1\40\1\102\1\103"+
    "\1\104\1\105\6\0\1\106\u01a2\0\2\106\326\0\u0100\106";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\1\3\1\4\1\5\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\5\26\1\27\1\30\1\31\20\26\1\32\1\33\1\34"+
    "\1\35\1\36\1\0\1\37\1\0\1\40\1\0\1\41"+
    "\1\0\1\42\1\43\1\44\1\45\1\46\1\0\1\47"+
    "\2\0\1\50\1\51\1\52\1\53\1\54\1\55\7\26"+
    "\1\56\2\0\14\26\1\57\1\26\1\60\2\26\1\61"+
    "\10\26\1\37\2\0\1\62\1\63\6\26\1\64\1\26"+
    "\1\65\1\0\1\66\1\0\5\26\1\67\4\26\1\70"+
    "\5\26\1\71\1\26\1\72\13\26\1\0\2\26\1\73"+
    "\3\26\1\74\5\26\1\75\1\76\2\26\1\77\1\0"+
    "\3\26\1\100\3\26\1\101\3\26\1\102\6\26\1\103"+
    "\1\0\5\26\1\104\1\105\1\106\2\26\1\107\1\26"+
    "\1\0\11\26\1\110\1\111\3\26\1\112\1\113\4\26"+
    "\1\114\1\115\3\26\1\116\2\26\1\117\6\26\1\120"+
    "\1\121\1\122\1\123\1\26\1\124\1\26\1\125\11\26"+
    "\1\126\1\127\1\130\1\131\1\132\1\133\1\134\3\26"+
    "\1\135\2\26\1\136\1\26\1\137\2\26\1\140\1\141"+
    "\2\26\1\142";

  private static int [] zzUnpackAction() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\216\0\325\0\u011c\0\u0163\0\u01aa\0\107"+
    "\0\u01f1\0\107\0\107\0\u0238\0\u027f\0\107\0\u02c6\0\u030d"+
    "\0\u0354\0\u039b\0\u03e2\0\107\0\107\0\u0429\0\u0470\0\u04b7"+
    "\0\107\0\107\0\u04fe\0\u0545\0\u058c\0\u05d3\0\u061a\0\107"+
    "\0\107\0\107\0\u0661\0\u06a8\0\u06ef\0\u0736\0\u077d\0\u07c4"+
    "\0\u080b\0\u0852\0\u0899\0\u08e0\0\u0927\0\u096e\0\u09b5\0\u09fc"+
    "\0\u0a43\0\u0a8a\0\107\0\107\0\107\0\107\0\107\0\u0ad1"+
    "\0\u0b18\0\u0b5f\0\107\0\u01f1\0\107\0\u0ba6\0\107\0\107"+
    "\0\107\0\107\0\u0bed\0\u0c34\0\107\0\u0c7b\0\u0cc2\0\107"+
    "\0\107\0\107\0\107\0\107\0\107\0\u0d09\0\u0d50\0\u0d97"+
    "\0\u0dde\0\u0e25\0\u0e6c\0\u0eb3\0\u0efa\0\u0f41\0\u0f88\0\u0fcf"+
    "\0\u1016\0\u105d\0\u10a4\0\u10eb\0\u1132\0\u1179\0\u11c0\0\u1207"+
    "\0\u124e\0\u1295\0\u12dc\0\u04fe\0\u1323\0\u136a\0\u13b1\0\u13f8"+
    "\0\u04fe\0\u143f\0\u1486\0\u14cd\0\u1514\0\u155b\0\u15a2\0\u15e9"+
    "\0\u1630\0\107\0\u1677\0\u16be\0\u16be\0\u0cc2\0\u1705\0\u174c"+
    "\0\u1793\0\u17da\0\u1821\0\u1868\0\u04fe\0\u18af\0\107\0\u18f6"+
    "\0\107\0\u193d\0\u1984\0\u19cb\0\u1a12\0\u1a59\0\u1aa0\0\u04fe"+
    "\0\u1ae7\0\u1b2e\0\u1b75\0\u1bbc\0\u04fe\0\u1c03\0\u1c4a\0\u1c91"+
    "\0\u1cd8\0\u1d1f\0\u04fe\0\u1d66\0\u04fe\0\u1dad\0\u1df4\0\u1e3b"+
    "\0\u1e82\0\u1ec9\0\u1f10\0\u1f57\0\u1f9e\0\u1fe5\0\u202c\0\u2073"+
    "\0\u20ba\0\u2101\0\u2148\0\u04fe\0\u218f\0\u21d6\0\u221d\0\u04fe"+
    "\0\u2264\0\u22ab\0\u22f2\0\u2339\0\u2380\0\u04fe\0\u04fe\0\u23c7"+
    "\0\u240e\0\u04fe\0\u2455\0\u249c\0\u24e3\0\u252a\0\u2571\0\u25b8"+
    "\0\u25ff\0\u2646\0\u04fe\0\u268d\0\u26d4\0\u271b\0\u04fe\0\u2762"+
    "\0\u27a9\0\u27f0\0\u2837\0\u287e\0\u28c5\0\u04fe\0\u290c\0\u2953"+
    "\0\u299a\0\u29e1\0\u2a28\0\u2a6f\0\u04fe\0\u2ab6\0\u04fe\0\u2afd"+
    "\0\u2b44\0\u04fe\0\u2b8b\0\u2bd2\0\u2c19\0\u2c60\0\u2ca7\0\u2cee"+
    "\0\u2d35\0\u2d7c\0\u2dc3\0\u2e0a\0\u2e51\0\u04fe\0\u04fe\0\u2e98"+
    "\0\u2edf\0\u2f26\0\u28c5\0\107\0\u2f6d\0\u2fb4\0\u2ffb\0\u3042"+
    "\0\u04fe\0\u2ab6\0\u3089\0\u30d0\0\u3117\0\107\0\u315e\0\u31a5"+
    "\0\u04fe\0\u31ec\0\u3233\0\u327a\0\u32c1\0\u3308\0\u334f\0\u04fe"+
    "\0\u04fe\0\u04fe\0\u04fe\0\u3396\0\u04fe\0\u33dd\0\u04fe\0\u3424"+
    "\0\u346b\0\u34b2\0\u34f9\0\u3540\0\u3587\0\u35ce\0\u3615\0\u365c"+
    "\0\u04fe\0\u04fe\0\u04fe\0\u04fe\0\u04fe\0\u04fe\0\u04fe\0\u36a3"+
    "\0\u36ea\0\u3731\0\u04fe\0\u3778\0\u37bf\0\u04fe\0\u3806\0\u04fe"+
    "\0\u384d\0\u3894\0\u04fe\0\u04fe\0\u38db\0\u3922\0\u04fe";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\2\33\1\34\1\33\1\35\1\33\1\36\2\33"+
    "\1\37\1\33\1\40\1\2\1\41\1\42\1\33\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\33\1\51\1\52"+
    "\1\33\1\53\1\33\1\54\1\55\1\56\1\57\1\60"+
    "\1\33\1\61\1\62\3\33\1\63\1\64\1\65\1\66"+
    "\1\2\110\0\3\3\132\0\1\67\57\0\2\70\1\0"+
    "\2\70\1\71\41\70\1\72\37\70\2\6\2\0\102\6"+
    "\30\0\1\73\57\0\2\74\1\0\6\74\1\75\35\74"+
    "\1\76\37\74\14\0\1\77\12\0\1\100\106\0\1\101"+
    "\106\0\1\102\101\0\2\103\26\0\1\104\63\0\1\105"+
    "\77\0\1\103\1\0\2\23\12\0\1\106\6\0\1\107"+
    "\4\0\1\23\4\0\1\106\20\0\1\107\26\0\1\103"+
    "\1\0\2\23\12\0\1\106\13\0\1\23\4\0\1\106"+
    "\55\0\1\110\1\111\106\0\1\112\1\113\105\0\1\114"+
    "\1\115\100\0\2\33\7\0\13\33\4\0\30\33\27\0"+
    "\2\33\7\0\13\33\4\0\27\33\1\116\27\0\2\33"+
    "\7\0\13\33\4\0\1\33\1\117\26\33\27\0\2\33"+
    "\7\0\13\33\4\0\1\33\1\120\26\33\27\0\2\33"+
    "\7\0\13\33\4\0\20\33\1\121\6\33\1\122\27\0"+
    "\2\33\7\0\13\33\4\0\4\33\1\123\10\33\1\124"+
    "\3\33\1\125\6\33\12\0\1\126\3\0\1\127\10\0"+
    "\2\33\7\0\13\33\4\0\16\33\1\130\1\33\1\131"+
    "\6\33\1\132\27\0\2\33\7\0\13\33\4\0\13\33"+
    "\1\133\2\33\1\134\11\33\27\0\2\33\7\0\13\33"+
    "\4\0\5\33\1\135\22\33\27\0\2\33\7\0\13\33"+
    "\4\0\13\33\1\136\10\33\1\137\1\33\1\140\1\33"+
    "\27\0\2\33\7\0\13\33\4\0\16\33\1\141\1\33"+
    "\1\142\7\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\143\22\33\27\0\2\33\7\0\13\33\4\0\6\33"+
    "\1\144\5\33\1\145\1\146\12\33\27\0\2\33\7\0"+
    "\13\33\4\0\16\33\1\147\11\33\27\0\2\33\7\0"+
    "\13\33\4\0\16\33\1\150\11\33\27\0\2\33\7\0"+
    "\13\33\4\0\20\33\1\151\7\33\27\0\2\33\7\0"+
    "\13\33\4\0\1\33\1\152\16\33\1\153\2\33\1\154"+
    "\4\33\27\0\2\33\7\0\13\33\4\0\1\33\1\155"+
    "\3\33\1\156\22\33\27\0\2\33\7\0\13\33\4\0"+
    "\22\33\1\157\5\33\27\0\2\33\7\0\13\33\4\0"+
    "\11\33\1\160\16\33\27\0\2\33\7\0\13\33\4\0"+
    "\11\33\1\161\16\33\5\0\2\70\1\0\2\70\1\162"+
    "\41\70\1\72\37\70\5\0\1\163\101\0\2\70\2\0"+
    "\102\70\1\0\2\74\2\0\102\74\23\0\2\103\12\0"+
    "\1\106\13\0\1\103\4\0\1\106\51\0\2\104\12\0"+
    "\1\106\13\0\1\104\4\0\1\106\44\0\1\164\1\0"+
    "\1\164\2\0\2\165\26\0\1\165\56\0\2\166\7\0"+
    "\5\166\12\0\7\166\50\0\2\33\7\0\13\33\4\0"+
    "\15\33\1\167\12\33\27\0\2\33\7\0\13\33\4\0"+
    "\13\33\1\170\14\33\27\0\2\33\7\0\13\33\4\0"+
    "\21\33\1\171\6\33\27\0\2\33\7\0\13\33\4\0"+
    "\23\33\1\172\4\33\27\0\2\33\7\0\13\33\4\0"+
    "\17\33\1\173\10\33\27\0\2\33\7\0\13\33\4\0"+
    "\4\33\1\174\23\33\27\0\2\33\7\0\13\33\4\0"+
    "\4\33\1\175\23\33\27\0\2\33\7\0\13\33\4\0"+
    "\21\33\1\176\6\33\5\0\2\126\1\0\2\126\1\177"+
    "\41\126\1\200\37\126\2\127\1\0\6\127\1\201\35\127"+
    "\1\202\37\127\22\0\2\33\7\0\13\33\4\0\16\33"+
    "\1\203\11\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\204\22\33\27\0\2\33\7\0\13\33\4\0\22\33"+
    "\1\205\5\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\206\22\33\27\0\2\33\7\0\13\33\4\0\15\33"+
    "\1\207\12\33\27\0\2\33\7\0\13\33\4\0\6\33"+
    "\1\210\21\33\27\0\2\33\7\0\13\33\4\0\11\33"+
    "\1\211\7\33\1\212\6\33\27\0\2\33\7\0\13\33"+
    "\4\0\5\33\1\213\22\33\27\0\2\33\7\0\13\33"+
    "\4\0\22\33\1\214\5\33\27\0\2\33\7\0\13\33"+
    "\4\0\20\33\1\215\7\33\27\0\2\33\7\0\13\33"+
    "\4\0\16\33\1\216\11\33\27\0\2\33\7\0\13\33"+
    "\4\0\26\33\1\217\1\33\27\0\2\33\7\0\13\33"+
    "\4\0\14\33\1\220\2\33\1\221\10\33\27\0\2\33"+
    "\7\0\13\33\4\0\22\33\1\222\5\33\27\0\2\33"+
    "\7\0\13\33\4\0\7\33\1\223\20\33\27\0\2\33"+
    "\7\0\13\33\4\0\15\33\1\224\4\33\1\225\5\33"+
    "\27\0\2\33\7\0\13\33\4\0\21\33\1\226\5\33"+
    "\1\227\27\0\2\33\7\0\13\33\4\0\11\33\1\230"+
    "\16\33\27\0\2\33\7\0\13\33\4\0\2\33\1\231"+
    "\15\33\1\232\7\33\27\0\2\33\7\0\13\33\4\0"+
    "\11\33\1\233\3\33\1\234\12\33\27\0\2\33\7\0"+
    "\13\33\4\0\22\33\1\235\5\33\27\0\2\33\7\0"+
    "\13\33\4\0\20\33\1\236\7\33\27\0\2\33\7\0"+
    "\13\33\4\0\15\33\1\237\12\33\27\0\2\33\7\0"+
    "\13\33\4\0\5\33\1\240\22\33\5\0\5\163\1\241"+
    "\101\163\22\0\2\165\26\0\1\165\56\0\2\33\7\0"+
    "\1\242\12\33\4\0\30\33\27\0\2\33\7\0\13\33"+
    "\4\0\21\33\1\172\6\33\27\0\2\33\7\0\13\33"+
    "\4\0\10\33\1\243\17\33\27\0\2\33\7\0\13\33"+
    "\4\0\5\33\1\244\22\33\27\0\2\33\7\0\13\33"+
    "\4\0\5\33\1\245\22\33\27\0\2\33\7\0\13\33"+
    "\4\0\20\33\1\246\7\33\27\0\2\33\7\0\13\33"+
    "\4\0\5\33\1\247\22\33\5\0\2\126\2\0\102\126"+
    "\1\0\2\127\2\0\102\127\23\0\2\33\7\0\13\33"+
    "\4\0\13\33\1\250\14\33\27\0\2\33\7\0\13\33"+
    "\4\0\1\33\1\251\26\33\27\0\2\33\7\0\13\33"+
    "\4\0\5\33\1\252\22\33\27\0\2\33\7\0\13\33"+
    "\4\0\1\33\1\253\26\33\27\0\2\33\7\0\13\33"+
    "\4\0\21\33\1\254\1\255\5\33\27\0\2\33\7\0"+
    "\13\33\4\0\6\33\1\256\21\33\27\0\2\33\7\0"+
    "\13\33\4\0\5\33\1\257\22\33\27\0\2\33\7\0"+
    "\13\33\4\0\15\33\1\260\12\33\27\0\2\33\7\0"+
    "\13\33\4\0\5\33\1\261\22\33\27\0\2\33\7\0"+
    "\13\33\4\0\14\33\1\262\13\33\12\0\1\263\14\0"+
    "\2\33\7\0\13\33\4\0\30\33\27\0\2\33\7\0"+
    "\13\33\4\0\23\33\1\264\4\33\27\0\2\33\7\0"+
    "\13\33\4\0\13\33\1\265\2\33\1\266\11\33\27\0"+
    "\2\267\7\0\13\33\4\0\5\33\1\270\22\33\27\0"+
    "\2\33\7\0\13\33\4\0\17\33\1\271\1\272\7\33"+
    "\27\0\2\33\7\0\13\33\4\0\21\33\1\273\6\33"+
    "\27\0\2\33\7\0\13\33\4\0\1\33\1\274\26\33"+
    "\27\0\2\33\7\0\13\33\4\0\24\33\1\275\3\33"+
    "\27\0\2\33\7\0\13\33\4\0\13\33\1\276\14\33"+
    "\27\0\2\33\7\0\13\33\4\0\5\33\1\277\22\33"+
    "\27\0\2\33\7\0\13\33\4\0\21\33\1\300\6\33"+
    "\27\0\2\33\7\0\13\33\4\0\7\33\1\301\20\33"+
    "\27\0\2\33\7\0\13\33\4\0\23\33\1\302\4\33"+
    "\27\0\2\33\7\0\13\33\4\0\11\33\1\303\11\33"+
    "\1\304\4\33\27\0\2\33\7\0\13\33\4\0\22\33"+
    "\1\305\5\33\27\0\2\33\7\0\13\33\4\0\25\33"+
    "\1\306\2\33\5\0\5\163\1\307\101\163\22\0\2\33"+
    "\7\0\13\33\4\0\20\33\1\310\7\33\27\0\2\33"+
    "\7\0\7\33\1\311\3\33\4\0\30\33\27\0\2\33"+
    "\7\0\10\33\1\312\2\33\4\0\30\33\27\0\2\33"+
    "\7\0\13\33\4\0\5\33\1\313\22\33\27\0\2\33"+
    "\7\0\13\33\4\0\20\33\1\314\7\33\27\0\2\33"+
    "\7\0\13\33\4\0\12\33\1\315\15\33\27\0\2\33"+
    "\7\0\13\33\4\0\21\33\1\316\6\33\27\0\2\33"+
    "\7\0\13\33\4\0\20\33\1\317\7\33\27\0\2\33"+
    "\7\0\13\33\4\0\22\33\1\320\5\33\27\0\2\33"+
    "\7\0\13\33\4\0\11\33\1\321\16\33\27\0\2\33"+
    "\7\0\13\33\4\0\22\33\1\322\5\33\27\0\2\33"+
    "\7\0\13\33\4\0\20\33\1\323\7\33\27\0\2\324"+
    "\7\0\5\324\13\0\6\324\50\0\2\33\7\0\13\33"+
    "\4\0\22\33\1\325\5\33\27\0\2\33\7\0\13\33"+
    "\4\0\5\33\1\326\22\33\27\0\2\33\7\0\13\33"+
    "\4\0\20\33\1\327\7\33\27\0\2\267\7\0\13\33"+
    "\4\0\30\33\27\0\2\33\7\0\13\33\4\0\20\33"+
    "\1\330\7\33\27\0\2\33\7\0\13\33\4\0\1\33"+
    "\1\331\26\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\332\22\33\27\0\2\33\7\0\13\33\4\0\2\33"+
    "\1\333\25\33\27\0\2\33\7\0\13\33\4\0\1\33"+
    "\1\334\26\33\27\0\2\33\7\0\13\33\4\0\11\33"+
    "\1\335\16\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\336\22\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\337\22\33\27\0\2\33\7\0\13\33\4\0\20\33"+
    "\1\340\7\33\27\0\2\33\7\0\13\33\4\0\15\33"+
    "\1\341\12\33\27\0\2\33\7\0\13\33\4\0\3\33"+
    "\1\342\24\33\27\0\2\343\7\0\13\33\4\0\30\33"+
    "\5\0\5\163\1\344\101\163\22\0\2\33\7\0\13\33"+
    "\4\0\20\33\1\345\7\33\27\0\2\33\7\0\13\33"+
    "\4\0\1\33\1\346\26\33\27\0\2\33\7\0\13\33"+
    "\4\0\1\33\1\347\26\33\27\0\2\33\7\0\13\33"+
    "\4\0\21\33\1\350\6\33\27\0\2\33\7\0\13\33"+
    "\4\0\22\33\1\351\5\33\27\0\2\352\7\0\13\33"+
    "\4\0\30\33\27\0\2\33\7\0\13\33\4\0\1\33"+
    "\1\353\26\33\27\0\2\33\7\0\13\33\4\0\15\33"+
    "\1\354\12\33\27\0\2\33\7\0\13\33\4\0\15\33"+
    "\1\355\12\33\12\0\1\356\14\0\2\324\7\0\5\324"+
    "\13\0\6\324\50\0\2\33\7\0\13\33\4\0\1\33"+
    "\1\357\26\33\27\0\2\33\7\0\13\33\4\0\14\33"+
    "\1\360\13\33\27\0\2\33\7\0\13\33\4\0\22\33"+
    "\1\361\5\33\27\0\2\33\7\0\13\33\4\0\6\33"+
    "\1\362\6\33\1\363\12\33\27\0\2\33\7\0\13\33"+
    "\4\0\27\33\1\364\27\0\2\33\7\0\13\33\4\0"+
    "\5\33\1\365\22\33\27\0\2\33\7\0\13\33\4\0"+
    "\13\33\1\366\14\33\27\0\2\33\7\0\13\33\4\0"+
    "\22\33\1\367\5\33\27\0\2\33\7\0\13\33\4\0"+
    "\3\33\1\370\24\33\27\0\2\33\7\0\13\33\4\0"+
    "\15\33\1\371\12\33\27\0\2\33\7\0\13\33\4\0"+
    "\7\33\1\372\20\33\27\0\2\33\7\0\13\33\4\0"+
    "\22\33\1\373\5\33\27\0\2\33\7\0\13\33\4\0"+
    "\1\33\1\374\26\33\27\0\2\33\7\0\13\33\4\0"+
    "\17\33\1\375\10\33\27\0\2\33\7\0\13\33\4\0"+
    "\14\33\1\376\13\33\27\0\2\33\7\0\13\33\4\0"+
    "\21\33\1\377\6\33\27\0\2\33\7\0\13\33\4\0"+
    "\15\33\1\u0100\12\33\27\0\2\33\7\0\13\33\4\0"+
    "\23\33\1\u0101\4\33\27\0\2\33\7\0\13\33\4\0"+
    "\1\33\1\u0102\26\33\27\0\2\33\7\0\13\33\4\0"+
    "\2\33\1\u0103\25\33\27\0\2\33\7\0\13\33\4\0"+
    "\5\33\1\u0104\22\33\27\0\2\33\7\0\13\33\4\0"+
    "\1\33\1\u0105\26\33\27\0\2\33\7\0\13\33\4\0"+
    "\1\33\1\u0106\26\33\27\0\2\33\7\0\13\33\4\0"+
    "\1\33\1\u0107\26\33\27\0\2\33\7\0\13\33\4\0"+
    "\15\33\1\u0108\12\33\27\0\2\33\7\0\13\33\4\0"+
    "\5\33\1\u0109\22\33\27\0\2\33\7\0\13\33\4\0"+
    "\5\33\1\u010a\22\33\27\0\2\33\7\0\13\33\4\0"+
    "\27\33\1\u010b\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\u010c\22\33\27\0\2\33\7\0\13\33\4\0\22\33"+
    "\1\u010d\5\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\u010e\22\33\27\0\2\33\7\0\13\33\4\0\13\33"+
    "\1\u010f\14\33\27\0\2\33\7\0\13\33\4\0\13\33"+
    "\1\u0110\14\33\27\0\2\33\7\0\13\33\4\0\15\33"+
    "\1\u0111\12\33\27\0\2\33\7\0\13\33\4\0\3\33"+
    "\1\u0112\24\33\27\0\2\33\7\0\13\33\4\0\13\33"+
    "\1\u0113\14\33\27\0\2\33\7\0\13\33\4\0\2\33"+
    "\1\u0114\25\33\27\0\2\33\7\0\13\33\4\0\22\33"+
    "\1\u0115\5\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\u0116\22\33\27\0\2\33\7\0\13\33\4\0\22\33"+
    "\1\u0117\5\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\u0118\22\33\27\0\2\33\7\0\13\33\4\0\13\33"+
    "\1\u0119\14\33\27\0\2\33\7\0\13\33\4\0\20\33"+
    "\1\u011a\7\33\27\0\2\33\7\0\13\33\4\0\21\33"+
    "\1\u011b\6\33\27\0\2\33\7\0\13\33\4\0\5\33"+
    "\1\u011c\22\33\27\0\2\33\7\0\13\33\4\0\1\33"+
    "\1\u011d\26\33\27\0\2\33\7\0\13\33\4\0\15\33"+
    "\1\u011e\12\33\27\0\2\33\7\0\13\33\4\0\22\33"+
    "\1\u011f\5\33\5\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[14697];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String[] ZZ_ERROR_MSG = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\1\1\2\11\2\1\1\11"+
    "\5\1\2\11\3\1\2\11\5\1\3\11\20\1\5\11"+
    "\1\0\1\1\1\0\1\11\1\0\1\11\1\0\4\11"+
    "\1\1\1\0\1\11\2\0\6\11\10\1\2\0\32\1"+
    "\1\11\2\0\12\1\1\11\1\0\1\11\1\0\36\1"+
    "\1\0\21\1\1\0\23\1\1\0\14\1\1\0\17\1"+
    "\1\11\11\1\1\11\61\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[287];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  protected int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  public _VyperLexer() {
    this((java.io.Reader)null);
  }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public _VyperLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  public final int getTokenStart() {
    return zzStartRead;
  }

  public final int getTokenEnd() {
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end, int initialState) {
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      {@code false}, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position {@code pos} from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 99: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 100: break;
          case 3:
            { return COMMENT;
            }
          // fall through
          case 101: break;
          case 4:
            { return PERCENT;
            }
          // fall through
          case 102: break;
          case 5:
            { return INTERSECTION;
            }
          // fall through
          case 103: break;
          case 6:
            { return LPAREN;
            }
          // fall through
          case 104: break;
          case 7:
            { return RPAREN;
            }
          // fall through
          case 105: break;
          case 8:
            { return MULT;
            }
          // fall through
          case 106: break;
          case 9:
            { return PLUS;
            }
          // fall through
          case 107: break;
          case 10:
            { return COMMA;
            }
          // fall through
          case 108: break;
          case 11:
            { return MINUS;
            }
          // fall through
          case 109: break;
          case 12:
            { return DOT;
            }
          // fall through
          case 110: break;
          case 13:
            { return DIV;
            }
          // fall through
          case 111: break;
          case 14:
            { return DECIMALNUMBER;
            }
          // fall through
          case 112: break;
          case 15:
            { return COLON;
            }
          // fall through
          case 113: break;
          case 16:
            { return SEMICOLON;
            }
          // fall through
          case 114: break;
          case 17:
            { return LESS;
            }
          // fall through
          case 115: break;
          case 18:
            { return ASSIGN;
            }
          // fall through
          case 116: break;
          case 19:
            { return MORE;
            }
          // fall through
          case 117: break;
          case 20:
            { return QUESTION;
            }
          // fall through
          case 118: break;
          case 21:
            { return DECORATOR;
            }
          // fall through
          case 119: break;
          case 22:
            { return IDENTIFIER;
            }
          // fall through
          case 120: break;
          case 23:
            { return LBRACKET;
            }
          // fall through
          case 121: break;
          case 24:
            { return RBRACKET;
            }
          // fall through
          case 122: break;
          case 25:
            { return CARET;
            }
          // fall through
          case 123: break;
          case 26:
            { return LBRACE;
            }
          // fall through
          case 124: break;
          case 27:
            { return UNION;
            }
          // fall through
          case 125: break;
          case 28:
            { return RBRACE;
            }
          // fall through
          case 126: break;
          case 29:
            { return TILDE;
            }
          // fall through
          case 127: break;
          case 30:
            { return NEQ;
            }
          // fall through
          case 128: break;
          case 31:
            { return STRINGLITERALDOUBLE;
            }
          // fall through
          case 129: break;
          case 32:
            { return PERCENT_ASSIGN;
            }
          // fall through
          case 130: break;
          case 33:
            { return STRINGLITERALSINGLE;
            }
          // fall through
          case 131: break;
          case 34:
            { return EXPONENT;
            }
          // fall through
          case 132: break;
          case 35:
            { return MULT_ASSIGN;
            }
          // fall through
          case 133: break;
          case 36:
            { return PLUS_ASSIGN;
            }
          // fall through
          case 134: break;
          case 37:
            { return MINUS_ASSIGN;
            }
          // fall through
          case 135: break;
          case 38:
            { return FIXEDNUMBER;
            }
          // fall through
          case 136: break;
          case 39:
            { return DIV_ASSIGN;
            }
          // fall through
          case 137: break;
          case 40:
            { return LSHIFT;
            }
          // fall through
          case 138: break;
          case 41:
            { return LESSEQ;
            }
          // fall through
          case 139: break;
          case 42:
            { return EQ;
            }
          // fall through
          case 140: break;
          case 43:
            { return TO;
            }
          // fall through
          case 141: break;
          case 44:
            { return MOREEQ;
            }
          // fall through
          case 142: break;
          case 45:
            { return RSHIFT;
            }
          // fall through
          case 143: break;
          case 46:
            { return AS;
            }
          // fall through
          case 144: break;
          case 47:
            { return IF;
            }
          // fall through
          case 145: break;
          case 48:
            { return IN;
            }
          // fall through
          case 146: break;
          case 49:
            { return OR;
            }
          // fall through
          case 147: break;
          case 50:
            { return SCIENTIFICNUMBER;
            }
          // fall through
          case 148: break;
          case 51:
            { return HEXNUMBER;
            }
          // fall through
          case 149: break;
          case 52:
            { return AND;
            }
          // fall through
          case 150: break;
          case 53:
            { return STRINGLITERALDOUBLEB;
            }
          // fall through
          case 151: break;
          case 54:
            { return STRINGLITERALSINGLEB;
            }
          // fall through
          case 152: break;
          case 55:
            { return DEF;
            }
          // fall through
          case 153: break;
          case 56:
            { return FOR;
            }
          // fall through
          case 154: break;
          case 57:
            { return LOG;
            }
          // fall through
          case 155: break;
          case 58:
            { return NOT;
            }
          // fall through
          case 156: break;
          case 59:
            { return BOOLEANLITERAL;
            }
          // fall through
          case 157: break;
          case 60:
            { return BOOL;
            }
          // fall through
          case 158: break;
          case 61:
            { return ELIF;
            }
          // fall through
          case 159: break;
          case 62:
            { return ELSE;
            }
          // fall through
          case 160: break;
          case 63:
            { return FROM;
            }
          // fall through
          case 161: break;
          case 64:
            { return INTM;
            }
          // fall through
          case 162: break;
          case 65:
            { return PASS;
            }
          // fall through
          case 163: break;
          case 66:
            { return PURE;
            }
          // fall through
          case 164: break;
          case 67:
            { return VIEW;
            }
          // fall through
          case 165: break;
          case 68:
            { return BREAK;
            }
          // fall through
          case 166: break;
          case 69:
            { return BYTES;
            }
          // fall through
          case 167: break;
          case 70:
            { return CLEAR;
            }
          // fall through
          case 168: break;
          case 71:
            { return EVENT;
            }
          // fall through
          case 169: break;
          case 72:
            { return RAISE;
            }
          // fall through
          case 170: break;
          case 73:
            { return RANGE;
            }
          // fall through
          case 171: break;
          case 74:
            { return UINTM;
            }
          // fall through
          case 172: break;
          case 75:
            { return MULTILINESTRINGTOKEN;
            }
          // fall through
          case 173: break;
          case 76:
            { return ASSERT;
            }
          // fall through
          case 174: break;
          case 77:
            { return BYTESM;
            }
          // fall through
          case 175: break;
          case 78:
            { return HEXLITERAL;
            }
          // fall through
          case 176: break;
          case 79:
            { return IMPORT;
            }
          // fall through
          case 177: break;
          case 80:
            { return PUBLIC;
            }
          // fall through
          case 178: break;
          case 81:
            { return RETURN;
            }
          // fall through
          case 179: break;
          case 82:
            { return STRING;
            }
          // fall through
          case 180: break;
          case 83:
            { return STRUCT;
            }
          // fall through
          case 181: break;
          case 84:
            { return HASHMAP;
            }
          // fall through
          case 182: break;
          case 85:
            { return ADDRESS;
            }
          // fall through
          case 183: break;
          case 86:
            { return PAYABLE;
            }
          // fall through
          case 184: break;
          case 87:
            { return PRIVATE;
            }
          // fall through
          case 185: break;
          case 88:
            { return DYNARRAY;
            }
          // fall through
          case 186: break;
          case 89:
            { return TYPENAME;
            }
          // fall through
          case 187: break;
          case 90:
            { return CONSTANT;
            }
          // fall through
          case 188: break;
          case 91:
            { return CONTINUE;
            }
          // fall through
          case 189: break;
          case 92:
            { return EXTERNAL;
            }
          // fall through
          case 190: break;
          case 93:
            { return INTERNAL;
            }
          // fall through
          case 191: break;
          case 94:
            { return IMMUTABLE;
            }
          // fall through
          case 192: break;
          case 95:
            { return INTERFACE;
            }
          // fall through
          case 193: break;
          case 96:
            { return IMPLEMENTS;
            }
          // fall through
          case 194: break;
          case 97:
            { return NONPAYABLE;
            }
          // fall through
          case 195: break;
          case 98:
            { return NONREENTRANT;
            }
          // fall through
          case 196: break;
          default:
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
